### ISSUE TITLE
User gets created and assigned membership level when user abandons

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-payfast#21]
Request from user:

"I have installed Paid Membership Pro software onto a site for a client and integrated it with PayFast as per their instructions.

I have established that if a user signs up by creating a username and a password and then clicks the PayFast button but does not complete their payment, the logins will still work for that user giving them access to digital content that is only for paid users.

How can I prevent this from happening? Is there not any code that only confirms the logins as valid once PayFast have returned a "payment confirmation" signal?"

**Comment by ideadude** [comment]
The answer we use for PayPal Standard which works in a similar way is that you need to setup your site so that only members can access the site or content you want to protect and users without membership cannot.

It would be too hard IMO to try to build a system that doesn't create the user up front (we need the ID for tracking for when the ITN message comes in).
